### ISSUE TITLE
升级2.2.5之后会忽略@Controller 扫描所有文件

### ISSUE THREAD

**Issue by jasine** [Ysj291823/egg-swagger-doc#42]
升级2.2.5之后会忽略@Controller，扫描所有文件和方法，当其他文件中没有接口注释时会报错
`egg-swagger-doc/lib/comment/index.js:14:47`

**Comment by jasine** [comment]
2.2.4是没问题的

**Comment by jc-lathander** [comment]
same issue

**Comment by Ysj291823** [comment]
我在linux和windows环境下测试了没有问题，可以提供报错信息吗？

**Comment by jc-lathander** [comment]
当 controller 文件没有带 @controller 标识的时候，扫描会报错
```
2019-02-18 13:14:10,301 ERROR 8421 nodejs.TypeError: Cannot read property 'filter' of null
    at Object.generateCommentBlocks (/Users/xxx/node_modules/egg-swagger-doc/lib/comment/index.js:14:47)
    at getTag_Path (/Users/xxx/node_modules/egg-swagger-doc/lib/document/index.js:91:28)
    at buildDocument (/Users/xxx/node_modules/egg-swagger-doc/lib/document/index.js:50:14)
    at documentInit (/Users/xxx/node_modules/egg-swagger-doc/lib/document/index.js:458:7)
    at module.exports.swaggerInit.app (/Users/xxx/node_modules/egg-swagger-doc/lib/index.js:10:3)
    at app.beforeStart (/Users/xxx/node_modules/egg-swagger-doc/app.js:8:5)
    at Object.callFn (/Users/xxx/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/xxx/node_modules/egg-core/lib/lifecycle.js:248:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
```

问题在于
```
    const block_regex = /\/\*\*([\s\S]*?)\*\//gm;
    let blocks = fileString.match(block_regex).filter(value => {
      return value.indexOf('ontroller') > -1 || value.indexOf('outer') > -1 || value.indexOf('gnore') > -1;
    });
```
如果 controller 文件没有注释的时候， match 返回为 null，这时候调用 .value 就会出错

**Comment by Ysj291823** [comment]
我知道了，是完全没有注释的情况下发生的。我这里加下判断。谢谢！

**Comment by Ysj291823** [comment]
it has been fixed
