### ISSUE TITLE
只要在ts文件中添加备注 @Controller时就会报错

### ISSUE THREAD

**Issue by Aqincheng** [Ysj291823/egg-swagger-doc#69]
2019-08-16 16:20:25,122 ERROR 15776 [-/127.0.0.1/-/0ms GET /] nodejs.Error: [egg-swagger-doc] error at post:/agent/checkUser ,the type of response parameter does not exit
    at generateResponse (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:370:17)
    at getTag_Path (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:139:35)
    at buildDocument (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:50:14)
    at documentInit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:497:7)
    at module.exports.swaggerInit.app (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\index.js:10:3)
    at app.beforeStart (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\app.js:8:5)
    at Object.callFn (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\utils\index.js:44:42)
    at process.nextTick (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

pid: 15776
hostname: USER-20190118FU

2019-08-16 16:20:25,124 ERROR 15776 nodejs.Error: [egg-swagger-doc] error at post:/agent/checkUser ,the type of response parameter does not exit
    at generateResponse (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:370:17)
    at getTag_Path (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:139:35)
    at buildDocument (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:50:14)
    at documentInit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\document\index.js:497:7)
    at module.exports.swaggerInit.app (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\lib\index.js:10:3)
    at app.beforeStart (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-swagger-doc\app.js:8:5)
    at Object.callFn (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\utils\index.js:44:42)
    at process.nextTick (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-core\lib\lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

pid: 15776
hostname: USER-20190118FU

2019-08-16 16:20:25,124 ERROR 15776 [app_worker] start error, exiting with code:1
[2019-08-16 16:20:25.130] [cfork:master:3236] worker:15776 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
2019-08-16 16:20:25,131 ERROR 12376 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 12376
hostname: USER-20190118FU

[2019-08-16 16:20:25.131] [cfork:master:3236] don't fork, because worker:15776 will be kill soon
2019-08-16 16:20:25,134 INFO 3236 [master] app_worker#21:15776 disconnect, suicide: false, state: disconnected, current workers: ["21"]
[2019-08-16 16:20:25.143] [cfork:master:3236] worker:15776 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-08-16 16:20:25,144 ERROR 3236 nodejs.AppWorkerDiedError: [master] app_worker#21:15776 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\master.js:510:21)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.cluster.on (C:\Users\Administrator\Desktop\5555\htetypescript\node_modules\egg-cluster\lib\master.js:353:22)
    at EventEmitter.emit (events.js:187:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AppWorkerDiedError"
pid: 3236
hostname: USER-20190118FU

**Comment by nerocho** [comment]
export class 改成 export default class 就行了，你八成是这么写的吧...
